// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDghjB1J30iqow5F6tcEm4f88UajeZS7CU",
    authDomain: "bukk-2e9a9.firebaseapp.com",
    projectId: "bukk-2e9a9",
    storageBucket: "bukk-2e9a9.appspot.com",
    messagingSenderId: "528312304991",
    appId: "1:528312304991:web:4237285ee1efd0f032e2ea",
    measurementId: "G-KE2N692FMY"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTi5nvVdfTMWrXKK0jbXFkfjKRr09cndM',
    appId: '1:690789521417:android:9e0cb79c01b66d922e40d8',
    messagingSenderId: '690789521417',
    projectId: 'klakonnect',
    storageBucket: 'klakonnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiH2AgjMsqaSAWj_uwF5AoEOHI3qVppv8',
    appId: '1:1073098243312:ios:bfe5bcb53fca0d8ae8d635',
    messagingSenderId: '1073098243312',
    projectId: 'schools-app-a6b04',
    storageBucket: 'schools-app-a6b04.appspot.com',
    androidClientId: '1073098243312-d2gngsm6g2qsirr9505o1gakc1bidini.apps.googleusercontent.com',
    iosClientId: '1073098243312-vfgsllj8fghhb0cdf5ni42ej52o5r0pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cpSchoolsApplication',
  );
}